### ISSUE TITLE
Example binary

### ISSUE THREAD

**Issue by symeonp** [quarkslab/whvp#1]
Hello!

Thanks for sharing this research, amazing tool. I also found the talk which is in French only unfortunately.
Could you please provide the demo binary showed in the demo as an example and perhaps some documentation?

Thanks so much!

**Comment by erynian** [comment]
Hello,
Unfortunately I can't share the demo binary (it is a part of our internal trainings). On the bright side, the tool is being revamped (other backends not just whvp + some documentation). I'll do a public release on our blog (https://blog.quarkslab.com/) probably in January. The blogpost (in English) will target a vulnerability in cng.sys (released by Google P0 and patched in November). It will be written as some kind of tutorial. 
I'll update this repository when it's done.

Cheers

**Comment by symeonp** [comment]
Fantastic, look forward to it, thank you so much!!

**Comment by symeonp** [comment]
Sorry to be pain, guess project gone a bit behind. Still plans on releasing it?
Thanks :)

**Comment by erynian** [comment]
Yes still planned sorry for the delay :(

**Comment by symeonp** [comment]
No worries!! I gathered you are busy, many thanks!
